src/account/urls.py
from django.urls import path
from .views import (LoginView, RegisterView, ProfileView, LogoutView, RestorePasswordView, SaveProfileView,
                    SetPasswordView, ActivateView)
from django.views.decorators.csrf import csrf_exempt

app_name = 'account'
urlpatterns = [
    path('', ProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('restore/', RestorePasswordView.as_view(), name='restore'),
    path('save_profile/', SaveProfileView.as_view(), name='save'),
    path('set_password/', SetPasswordView.as_view(), name='set_password'),
    path('activate/', ActivateView.as_view(), name='activate'),
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include
from landing.views import IndexView as Landing
from landing.views import DownloadView
# from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('', Landing.as_view(), name='index'),
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('download/', DownloadView.as_view(), name='download'),
]

src/account/models.py
from django.db import models
from custom_user.models import EmailUser as User
from django.utils.translation import gettext as _


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    display_name = models.CharField(_('display name'), max_length=64)
    site = models.URLField(_('site'), max_length=256)

src/account/views.py
from django.views.generic import TemplateView, RedirectView, View
from django.shortcuts import reverse
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.conf import settings


class IndexView(TemplateView):
    template_name = 'base.html'


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'account/profile.html'


class LoginView(TemplateView):
    template_name = 'account/login.html'

    def post(self, request):
        username = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return JsonResponse(dict(
                success=True,
                url=request.GET.get('next') or settings.LOGIN_REDIRECT_URL
            ))
        else:
            return JsonResponse(dict(
                success=False,
                error='Wrong email or password'
            ))


class LogoutView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('account:login')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class RegisterView(TemplateView):
    template_name = 'account/register.html'

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data()
        ctx['enabled'] = settings.ALLOW_REGISTER
        return self.render_to_response(ctx)


class RestorePasswordView(TemplateView):
    template_name = 'account/restore.html'

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data()
        ctx['enabled'] = settings.EMAIL_IS_ACTIVE
        return self.render_to_response(ctx)


class SaveProfileView(LoginRequiredMixin, View):
    def post(self, request):
        print(request.POST.dict())
        return JsonResponse(dict(
            success=True
        ))


class SetPasswordView(LoginRequiredMixin, View):
    pass


class ActivateView(TemplateView):
    template_name = 'account/activated.html'

src/landing/views.py
from django.views.generic import TemplateView
from django.conf import settings
import os, re


class IndexView(TemplateView):
    template_name = 'landing/index_ru.html'

    def get(self, request, *args, **kwargs):
        lang = 'ru'
        if 'en' in request.GET.dict():
            lang = 'en'
            self.template_name = 'landing/index_en.html'
        ctx = self.get_context_data()
        ctx['lang'] = lang
        return self.render_to_response(ctx)


class DownloadView(TemplateView):
    template_name = 'landing/download.html'

    def get(self, request, *args, **kwargs):
        ctx = self.get_context_data()
        data = {}
        for OS in ['win', 'lin', 'mac']:
            data[OS] = get_release(OS)
        ctx['downloads'] = data
        return self.render_to_response(ctx)


def get_release(OS):
    d = os.path.join(settings.DOWNLOAD_ROOT, OS)
    print(d)
    if not os.path.exists(d):
        print('Path not exists:', d)
        return
    # releases = sorted(os.listdir(d))
    releases = sorted(os.listdir(d), key=lambda f: [int(x) for x in re.findall(r"\d+", f)])
    if releases:
        return dict(
            name=releases[-1],
            url='/media/downloads/{}/{}'.format(OS, releases[-1])
        )

src/landing/templates/landing/download.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{% block title %}
Download
{% endblock %}

{% block header_title %}
Download
{% endblock %}

{% block breadcrumbs %}
    <li class="active">Download</li>
{% endblock %}





{% block content %}
<section class="text-center">

				<h1 class="margin-bottom-20 size-30 font-lato weight-500">
                    DOWNLOAD FENX INSTALLER
                </h1>
				<p class="size-20 font-lato weight-400">FenxPipeline still under development. Please read <a href="http://docs.fenxpipeline.com/manual/tester/" style="color: white">testers information</a> before install.</p>

			</section>
			<!-- / -->
			<!-- -->
			<section class="text-center">
				<div class="container">

					<div class="row">
                        {% if lin %}

                        {% endif %}
						<div class="col-md-4 col-sm-4">
{#							<i class="fa fa-info-circle fa-5x"></i>#}
                            <img class="d-flex mr-3" data-src="holder.js/64x64" alt="64x64" src="{% static "assets/images/lin.png" %}" data-holder-rendered="true" style="width: 64px; height: 64px;" />
							<h2 class="size-17 margin-top-6">Linux Ubuntu 16+</h2>
                            {% if downloads.lin %}
                                <a href="{{ downloads.lin.url }}">{{ downloads.lin.name }}</a>
                                {% else %}
                                <p class="text-muted">Under Development</p>
                            {% endif %}
						</div>

						<div class="col-md-4 col-sm-4">
							<img class="d-flex mr-3" data-src="holder.js/64x64" alt="64x64" src="{% static "assets/images/win.png" %}" data-holder-rendered="true" style="width: 64px; height: 64px;" />
							<h2 class="size-17 margin-top-6">Windows 7+ x64</h2>
                            {% if downloads.win %}
                                <a href="{{ downloads.win.url }}">{{ downloads.win.name }}</a>
                                {% else %}
                                <p class="text-muted">Under Development</p>
                            {% endif %}
{#							<p class="text-muted">Unfortunately we do not know the exact downtime, but we esitmate less than an hour.</p>#}
						</div>

						<div class="col-md-4 col-sm-4">
{#							<i class="fa fa-comments-o fa-5x"></i>#}
                            <img class="d-flex mr-3" data-src="holder.js/64x64" alt="64x64" src="{% static "assets/images/mac.png" %}" data-holder-rendered="true" style="width: 64px; height: 64px;" />
							<h2 class="size-17 margin-top-6">MacOS</h2>
							{% if downloads.mac %}
                                <a href="{{ downloads.mac.url }}">{{ downloads.mac.name }}</a>
                                {% else %}
                                <p class="text-muted">Under Development</p>
                            {% endif %}
						</div>
                        <h4><a href="http://docs.fenxpipeline.com/manual/tester/">TESTERS INFORMATION</a></h4>
					</div>

				</div>
			</section>
{% endblock %}

src/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<!--[if IE 8]>			<html class="ie ie8"> <![endif]-->
<!--[if IE 9]>			<html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]><!-->	<html> <!--<![endif]-->
	<head>
		<meta charset="utf-8" />
		<title>{% block title %}FenxPipeline{% endblock %}</title>
		<meta name="keywords" content="FenxPieline,Modules" />
		<meta name="description" content="" />
		<meta name="Author" content="paulwinex" />
        <link rel="icon" href="{% static "/assets/favicon.ico" %}">

		<!-- mobile settings -->
		<meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
		<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

		<!-- WEB FONTS : use %7C instead of | (pipe) -->
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700" rel="stylesheet" type="text/css" />

		<!-- CORE CSS -->
		<link href="{% static "assets/plugins/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />

		<!-- THEME CSS -->
		<link href="{% static "assets/css/essentials.css" %}"  rel="stylesheet" type="text/css" />
		<link href="{% static "assets/css/layout.css" %}"  rel="stylesheet" type="text/css" />

		<!-- PAGE LEVEL SCRIPTS -->
		<link href="{% static "assets/css/header-1.css" %}"  rel="stylesheet" type="text/css" />
		<link href="{% static "assets/css/custom.css" %}"  rel="stylesheet" type="text/css" />
{#		<link href="{% static "assets/css/color_scheme/green.css" %}"  rel="stylesheet" type="text/css" id="color_scheme" />#}
		<link href="{% static "assets/css/color_scheme/lightgrey.css" %}"  rel="stylesheet" type="text/css" id="color_scheme" />
        <link id="css_dark_skin" href="{% static "assets/css/layout-dark.css" %}" rel="stylesheet" type="text/css" title="dark">
        <style>
            a.logo > img {
                height: 50px;
            }
            section {
                padding: 20px 0;
            }
            a:hover{
                color: white;
            }
            section.page-header {
                padding: 10px 0 10px 0;
                background-color: #121212;
            }

        </style>
        {% block head %}

        {% endblock %}

	</head>

	<!--
		AVAILABLE BODY CLASSES:

		smoothscroll 			= create a browser smooth scroll
		enable-animation		= enable WOW animations

		bg-grey					= grey background
		grain-grey				= grey grain background
		grain-blue				= blue grain background
		grain-green				= green grain background
		grain-blue				= blue grain background
		grain-orange			= orange grain background
		grain-yellow			= yellow grain background

		boxed 					= boxed layout
		pattern1 ... patern11	= pattern background
		menu-vertical-hide		= hidden, open on click

		BACKGROUND IMAGE [together with .boxed class]
		data-background="assets/images/boxed_background/1.jpg"
	-->
	<body class="smoothscroll">

		<!-- SLIDE TOP -->
{#		<div id="slidetop">#}
{##}
{#			<div class="container">#}
{##}
{#				<div class="row">#}
{##}
{#					<div class="col-md-4">#}
{#						<h6><i class="icon-heart"></i> WHY SMARTY?</h6>#}
{#						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas metus nulla, commodo a sodales sed, dignissim pretium nunc. Nam et lacus neque. Ut enim massa, sodales tempor convallis et, iaculis ac massa. </p>#}
{#					</div>#}
{##}
{#					<div class="col-md-4">#}
{#						<h6><i class="icon-attachment"></i> RECENTLY VISITED</h6>#}
{#						<ul class="list-unstyled">#}
{#							<li><a href="#"><i class="fa fa-angle-right"></i> Consectetur adipiscing elit amet</a></li>#}
{#							<li><a href="#"><i class="fa fa-angle-right"></i> This is a very long text, very very very very very very very very very very very very </a></li>#}
{#							<li><a href="#"><i class="fa fa-angle-right"></i> Lorem ipsum dolor sit amet</a></li>#}
{#							<li><a href="#"><i class="fa fa-angle-right"></i> Dolor sit amet,consectetur adipiscing elit amet</a></li>#}
{#							<li><a href="#"><i class="fa fa-angle-right"></i> Consectetur adipiscing elit amet,consectetur adipiscing elit</a></li>#}
{#						</ul>#}
{#					</div>#}
{##}
{#					<div class="col-md-4">#}
{#						<h6><i class="icon-envelope"></i> CONTACT INFO</h6>#}
{#						<ul class="list-unstyled">#}
{#							<li><b>Address:</b> PO Box 21132, Here Weare St, <br /> Melbourne, Vivas 2355 Australia</li>#}
{#							<li><b>Phone:</b> 1-800-565-2390</li>#}
{#							<li><b>Email:</b> <a href="mailto:support@yourname.com">support@yourname.com</a></li>#}
{#						</ul>#}
{#					</div>#}
{##}
{#				</div>#}
{##}
{#			</div>#}
{##}
{#			<a class="slidetop-toggle" href="#"><!-- toggle button --></a>#}
{##}
{#		</div>#}
		<!-- /SLIDE TOP -->


		<!-- wrapper -->
		<div id="wrapper" style="background-color: #333;">

			<!--
				AVAILABLE HEADER CLASSES

				Default nav height: 96px
				.header-md 		= 70px nav height
				.header-sm 		= 60px nav height

				.noborder 		= remove bottom border (only with transparent use)
				.transparent	= transparent header
				.translucent	= translucent header
				.sticky			= sticky header
				.static			= static header
				.dark			= dark header
				.bottom			= header on bottom

				shadow-before-1 = shadow 1 header top
				shadow-after-1 	= shadow 1 header bottom
				shadow-before-2 = shadow 2 header top
				shadow-after-2 	= shadow 2 header bottom
				shadow-before-3 = shadow 3 header top
				shadow-after-3 	= shadow 3 header bottom

				.clearfix		= required for mobile menu, do not remove!

				Example Usage:  class="clearfix sticky header-sm transparent noborder"
			-->
			<div id="header" class="sticky clearfix">

				<!-- TOP NAV -->
				<header id="topNav">
					<div class="container">

						<!-- Mobile Menu Button -->
						<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
							<i class="fa fa-bars menu-button"></i>
						</button>

						<!-- BUTTONS -->
						<ul class="pull-right nav nav-pills nav-second-main">

							<!-- SEARCH -->
							<!-- /SEARCH -->

							<!-- QUICK SHOP CART -->
							<!-- /QUICK SHOP CART -->

						</ul>
						<!-- /BUTTONS -->

						<!-- Logo -->
						<a class="logo pull-left" href="/">
							<img src="{% static "assets/img/fenx.png" %}" style="height: 50px;" alt="" />
						</a>

						<!--
							Top Nav

							AVAILABLE CLASSES:
							submenu-dark = dark sub menu
						-->
						<div class="navbar-collapse pull-right nav-main-collapse collapse">
							<nav class="nav-main">

								<!--
									NOTE

									For a regular link, remove "dropdown" class from LI tag and "dropdown-toggle" class from the href.
									Direct Link Example:

									<li>
										<a href="#">HOME</a>
									</li>
								-->
								<ul id="topMain" class="nav nav-pills nav-main">
                                    <li>
										<a href="http://docs.fenxpipeline.com/" target="_blank" class="side-menu-link">DOCUMENTATION</a>
									</li>
                                    <li>
										<a href="{% url "download" %}" class="side-menu-link">DOWNLOAD</a>
									</li>

									<li class="dropdown"><!-- HOME -->
{#										<a href="http://docs.fenxpipeline.com/">#}
{#											DOWNLOAD#}
{#										</a>#}
                                        <a class="dropdown-toggle side-menu-link" href="" >
											MODULES
										</a>

										<ul class="dropdown-menu">
											<li><a href="{% url "modules:index" %}" class="side-menu-link">LIBRARY</a></li>
											<li><a href="{% url "modules:my_modules" %}" class="side-menu-link">MY MODULES</a></li>
											<li><a href="{% url "modules:register" %}" class="side-menu-link">REGISTER NEW MODULE</a></li>
										</ul>

									</li>
                                    {% if user.is_authenticated %}
                                    <li class="dropdown">
										<a class="dropdown-toggle side-menu-link" href="#">
											{{ user|upper }}
										</a>
                                            <ul class="dropdown-menu">
                                                <li><a href="{% url "account:profile" %}" class="side-menu-link">PROGILE</a></li>
                                                <li><a href="{% url "account:logout" %}" class="side-menu-link">LOGOUT</a></li>
                                            </ul>
									</li>
                                    {% else %}
                                    <li class="dropdown">
                                        <a href="{% url "account:login" %}" class="side-menu-link">LOGIN</a>
                                    </li>
                                    {% endif %}
								</ul>
							</nav>
						</div>

					</div>
				</header>
				<!-- /Top Nav -->

			</div>


			<!--
				PAGE HEADER

				CLASSES:
					.page-header-xs	= 20px margins
					.page-header-md	= 50px margins
					.page-header-lg	= 80px margins
					.page-header-xlg= 130px margins
					.dark			= dark page header

					.shadow-before-1 	= shadow 1 header top
					.shadow-after-1 	= shadow 1 header bottom
					.shadow-before-2 	= shadow 2 header top
					.shadow-after-2 	= shadow 2 header bottom
					.shadow-before-3 	= shadow 3 header top
					.shadow-after-3 	= shadow 3 header bottom
			-->
			<section class="page-header">
				<div class="container">

					<h1>{% block header_title %}Home{% endblock %}</h1>

					<!-- breadcrumbs -->
					<ol class="breadcrumb">
						<li><a href="{% url "index" %}">Home</a></li>
                    {% block breadcrumbs %}
{#						<li class="active">Example</li>#}
                    {% endblock %}
					</ol><!-- /breadcrumbs -->

				</div>
			</section>
			<!-- /PAGE HEADER -->




			<!-- -->
			<section>
				<div class="container">

					{% block content %}

					{% endblock %}

				</div>
			</section>
			<!-- / -->




			<!-- FOOTER -->
{#			<footer id="footer" class="sticky">#}
{##}
{#				<div class="copyright">#}
{#					<div class="container">#}
{#						<ul class="pull-right nomargin list-inline mobile-block">#}
{#							<li><a href="#">Terms &amp; Conditions</a></li>#}
{#							<li>&bull;</li>#}
{#							<li><a href="#">Privacy</a></li>#}
{#						</ul>#}
{#						&copy; All Rights Reserved, FenxPipeline#}
{#					</div>#}
{#				</div>#}
{##}
{#			</footer>#}
			<!-- /FOOTER -->

		</div>
		<!-- /wrapper -->


		<!-- SCROLL TO TOP -->
		<a href="#" id="toTop"></a>


		<!-- PRELOADER -->
{#		<div id="preloader">#}
{#			<div class="inner">#}
{#				<span class="loader"></span>#}
{#			</div>#}
{#		</div>#}
        <!-- /PRELOADER -->


		<!-- JAVASCRIPT FILES -->
{#		<script type="text/javascript">var plugin_path = 'assets/plugins/';</script>#}
		<script type="text/javascript">var plugin_path = "{% static "assets/plugins/" %}";</script>
		<script type="text/javascript" src="{% static "assets/plugins/jquery/jquery-2.1.4.min.js" %}"></script>

		<script type="text/javascript" src="{% static "assets/js/scripts.js" %}"></script>

        {% block scripts %}

        {% endblock %}

		<!-- STYLESWITCHER - REMOVE -->
{#		<script async type="text/javascript" src="{% static "assets/plugins/styleswitcher/styleswitcher.js" %}"></script>#}
	</body>
</html>